#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// FORWARD DECLARATIONS


namespace DefaultButtonStyle { class UDefaultButtonStyle_C; }

namespace DefaultButtonStyle_0 { class UDefaultButtonStyle_C; }

namespace LoadoutCategory { struct FLoadoutCategory; }

namespace VivoxCore { enum class ELoginState : uint8; }


namespace ReadyOrNot
{
	struct FLoadoutCategory;
	enum class ELoginState : uint8;
}
